import {
  Category,
  Product,
  DeliveryZone,
  Order,
  CustomRequest,
  Customer,
} from "@/types";

// -----------------------------------------------------------------------
// DEMO / SEED DATA
// This data powers the storefront preview before a real Supabase project
// is connected (see README "Mode démo"). It is intentionally separated
// from `services/*.ts`, which is where real Supabase queries live, so
// nothing here is ever mistaken for production content — see spec §37.
// -----------------------------------------------------------------------

export const demoCategories: Category[] = [
  {
    id: "cat-amigurumi",
    name: "Amigurumi",
    slug: "amigurumi",
    description: "Petits personnages et animaux au crochet, doux et pleins de caractère.",
    image_url: "/demo/ours-amigurumi.svg",
    sort_order: 1,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-poupees",
    name: "Poupées",
    slug: "poupees",
    description: "Poupées uniques, cousues et habillées à la main.",
    image_url: "/demo/poupee-crochet.svg",
    sort_order: 2,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-fleurs",
    name: "Fleurs & Bouquets",
    slug: "fleurs-bouquets",
    description: "Des bouquets qui ne fanent jamais.",
    image_url: "/demo/bouquet-fleurs.svg",
    sort_order: 3,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-porte-cles",
    name: "Porte-clés",
    slug: "porte-cles",
    description: "De petites attentions à offrir ou s'offrir.",
    image_url: "/demo/porte-cles-coeur.svg",
    sort_order: 4,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-sacs",
    name: "Sacs",
    slug: "sacs",
    description: "Sacs et accessoires tissés main.",
    image_url: "/demo/sac-crochet.svg",
    sort_order: 5,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-decoration",
    name: "Décoration",
    slug: "decoration",
    description: "Pour une maison plus douce.",
    image_url: "/demo/panier-decoration.svg",
    sort_order: 6,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "cat-cadeaux",
    name: "Cadeaux",
    slug: "cadeaux",
    description: "Des idées cadeaux faites avec amour.",
    image_url: "/demo/cadeau-etoile.svg",
    sort_order: 7,
    is_enabled: true,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
];

export const demoProducts: Product[] = [];

export const demoDeliveryZones: DeliveryZone[] = [
  { id: "dz-alger", wilaya: "Alger", fee: 400, is_enabled: true, note: null },
  { id: "dz-oran", wilaya: "Oran", fee: 500, is_enabled: true, note: null },
  { id: "dz-mostaganem", wilaya: "Mostaganem", fee: 450, is_enabled: true, note: null },
  { id: "dz-constantine", wilaya: "Constantine", fee: 600, is_enabled: true, note: null },
  { id: "dz-blida", wilaya: "Blida", fee: 450, is_enabled: true, note: null },
  { id: "dz-tlemcen", wilaya: "Tlemcen", fee: 550, is_enabled: true, note: null },
  { id: "dz-setif", wilaya: "Sétif", fee: 600, is_enabled: true, note: null },
  { id: "dz-annaba", wilaya: "Annaba", fee: 650, is_enabled: true, note: null },
];

export const demoOrders: Order[] = [
  {
    id: "ord-1",
    order_number: "CB-AH-2026-0041",
    customer_name: "Sarah Bendaoud",
    customer_phone: "0551223344",
    wilaya: "Oran",
    commune: "Es Senia",
    address: "12 rue des Oliviers",
    delivery_instructions: null,
    items: [
      {
        id: "oi-1",
        order_id: "ord-1",
        product_id: "p-ourson-rose",
        product_name: "Ourson au crochet",
        product_image: "/demo/ours-amigurumi.svg",
        unit_price: 2500,
        quantity: 1,
        options: { color: "Rose" },
        line_total: 2500,
      },
      {
        id: "oi-2",
        order_id: "ord-1",
        product_id: "p-bouquet-eternel",
        product_name: "Bouquet éternel rose & ivoire",
        product_image: "/demo/bouquet-fleurs.svg",
        unit_price: 4000,
        quantity: 1,
        options: { color: "Blanc/Rose" },
        line_total: 4000,
      },
    ],
    subtotal: 6500,
    delivery_fee: 500,
    total: 7000,
    notes: "Je souhaite un petit mot cadeau si possible 💗",
    status: "confirmee",
    created_at: "2026-08-20T09:12:00Z",
    updated_at: "2026-08-21T08:00:00Z",
  },
  {
    id: "ord-2",
    order_number: "CB-AH-2026-0040",
    customer_name: "Imene Kaci",
    customer_phone: "0661998877",
    wilaya: "Alger",
    commune: "Bab Ezzouar",
    address: "45 cité des Frères",
    delivery_instructions: "Appeler avant de livrer",
    items: [
      {
        id: "oi-3",
        order_id: "ord-2",
        product_id: "p-porte-cle-coeur",
        product_name: "Porte-clés cœur",
        product_image: "/demo/porte-cles-coeur.svg",
        unit_price: 900,
        quantity: 3,
        options: { color: "Rose" },
        line_total: 2700,
      },
    ],
    subtotal: 2700,
    delivery_fee: 400,
    total: 3100,
    notes: null,
    status: "nouvelle",
    created_at: "2026-08-29T14:32:00Z",
    updated_at: "2026-08-29T14:32:00Z",
  },
  {
    id: "ord-3",
    order_number: "CB-AH-2026-0039",
    customer_name: "Sarah Bendaoud",
    customer_phone: "0551223344",
    wilaya: "Oran",
    commune: "Es Senia",
    address: "12 rue des Oliviers",
    delivery_instructions: null,
    items: [
      {
        id: "oi-4",
        order_id: "ord-3",
        product_id: "p-plante-deco",
        product_name: "Petite plante en pot",
        product_image: "/demo/plante-crochet.svg",
        unit_price: 2200,
        quantity: 2,
        options: {},
        line_total: 4400,
      },
    ],
    subtotal: 4400,
    delivery_fee: 500,
    total: 4900,
    notes: null,
    status: "livree",
    created_at: "2026-08-05T11:00:00Z",
    updated_at: "2026-08-10T09:00:00Z",
  },
];

export const demoCustomRequests: CustomRequest[] = [
  {
    id: "cr-1",
    request_number: "CUSTOM-2026-0028",
    customer_name: "Yasmine Haddad",
    customer_phone: "0770112233",
    wilaya: "Mostaganem",
    commune: "Centre",
    address: "8 rue de la Plage",
    creation_type: "poupee",
    description:
      "Je voudrais une poupée inspirée de ma fille, avec une robe rose et des cheveux bruns bouclés, pour son anniversaire.",
    colors: ["Rose", "Marron"],
    size: "moyen",
    custom_dimensions: null,
    quantity: 1,
    occasion: "anniversaire",
    desired_date: "2026-10-15",
    budget: 7000,
    notes: "Merci de me confirmer la date exacte de livraison possible.",
    images: [],
    status: "nouvelle_demande",
    admin_notes: null,
    created_at: "2026-09-01T16:20:00Z",
    updated_at: "2026-09-01T16:20:00Z",
  },
  {
    id: "cr-2",
    request_number: "CUSTOM-2026-0027",
    customer_name: "Nour El Houda",
    customer_phone: "0555667788",
    wilaya: "Alger",
    commune: "Hydra",
    address: "3 rue des Frères Bouadou",
    creation_type: "bouquet",
    description: "Un bouquet aux tons pastel pour un mariage, environ 25 tiges.",
    colors: ["Rose", "Lavande", "Blanc"],
    size: "grand",
    custom_dimensions: null,
    quantity: 1,
    occasion: "mariage",
    desired_date: "2026-11-02",
    budget: null,
    notes: null,
    images: [],
    status: "devis_envoye",
    admin_notes: "Devis envoyé le 30/08 — en attente de retour.",
    created_at: "2026-08-25T10:00:00Z",
    updated_at: "2026-08-30T12:00:00Z",
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Sarah Bendaoud",
    phone: "0551223344",
    wilaya: "Oran",
    orders_count: 2,
    total_spent: 11900,
    custom_requests_count: 0,
    last_order_at: "2026-08-20T09:12:00Z",
    created_at: "2026-08-05T11:00:00Z",
  },
  {
    id: "cust-2",
    name: "Imene Kaci",
    phone: "0661998877",
    wilaya: "Alger",
    orders_count: 1,
    total_spent: 3100,
    custom_requests_count: 0,
    last_order_at: "2026-08-29T14:32:00Z",
    created_at: "2026-08-29T14:32:00Z",
  },
  {
    id: "cust-3",
    name: "Yasmine Haddad",
    phone: "0770112233",
    wilaya: "Mostaganem",
    orders_count: 0,
    total_spent: 0,
    custom_requests_count: 1,
    last_order_at: null,
    created_at: "2026-09-01T16:20:00Z",
  },
];